Repository PatrykKuniczak/YT_Notifier, pull requests merged in 2023-12, with the labels that each got.

#182 feat/Fetching user videos
  nest-app/src/swagger/response-examples/user-yt-videos.response.ts
  nest-app/src/user-yt-videos/user-yt-videos.service.ts
  react-app/manifest.js
  react-app/public/locales/en/translation.json
  react-app/public/locales/pl/translation.json
  react-app/src/pages/background/index.ts
  react-app/src/pages/content/components/home/app.tsx
  react-app/src/pages/popup/components/video/section/article/authorInfo/author-info.tsx
  react-app/src/pages/popup/components/video/section/article/video-article.tsx
  react-app/src/pages/popup/components/video/section/article/videoInfo/video-info.ts
  react-app/src/pages/popup/components/video/section/article/videoInfo/video-infos.tsx
  react-app/src/pages/popup/layouts/navbar.tsx
  react-app/src/pages/popup/routes/videos.route.tsx
  react-app/utils/data/mixins/scrollbar-mixin.ts
  react-app/utils/endpoints/urls.ts
  react-app/utils/interfaces/index.ts
  react-app/utils/libs/internationalization/index.ts
Labels: enhancement, frontend, backend

#185 fix/check if user playlist exists before open window
  nest-app/src/user-yt-videos/user-yt-videos.controller.ts
  nest-app/src/user-yt-videos/user-yt-videos.service.ts
  react-app/public/locales/en/translation.json
  react-app/public/locales/pl/translation.json
  react-app/src/pages/popup/components/video/section/article/videoInfo/video-infos.tsx
  react-app/src/pages/popup/layouts/navbar.tsx
  react-app/utils/endpoints/urls.ts
Labels: bug, frontend, backend

#189 fix/loading on changing user state
  react-app/package-lock.json
  react-app/package.json
  react-app/src/pages/popup/Popup.tsx
  react-app/src/pages/popup/pages/auth/auth.page.tsx
  react-app/src/pages/popup/pages/home/home.page.tsx
  react-app/src/pages/popup/pages/protected.page.tsx
  react-app/src/pages/popup/providers-wrapper.tsx
  react-app/utils/hooks/with-error-boundary.tsx
  react-app/utils/interfaces/index.ts
Labels: bug, frontend

#181 fix/ delete account modal is broken
  react-app/src/pages/popup/components/shared/delete-modal/modal-content.tsx
Labels: bug, frontend

#187 feat/collecting and downloading errors data for user machine
  nest-app/.eslintignore
  nest-app/package.json
  nest-app/src/database/migrations/1701807327989-change-error-message-type.ts
  nest-app/src/database/migrations/1701808344010-remove-unnecessary-key-word-table.ts
  nest-app/src/error-logs/dto/create-key-word.dto.ts
  nest-app/src/error-logs/error-logs.service.ts
  nest-app/src/error-logs/model/error-logs.entity.ts
  nest-app/src/key-words/key-words.service.ts
  nest-app/src/key-words/model/key-words.entity.ts
  nest-app/src/user-yt-videos/user-yt-videos.service.ts
  nest-app/src/users/model/users.entity.ts
  nest-app/src/users/users.service.ts
  react-app/public/locales/en/translation.json
  react-app/public/locales/pl/translation.json
  react-app/src/pages/popup/components/shared/profile.tsx
  react-app/src/pages/popup/routes/videos.route.tsx
  react-app/utils/endpoints/urls.ts
Labels: bug, enhancement, frontend, backend

#188 Improvement/improve a11y #83
  react-app/.eslintrc
  react-app/package-lock.json
  react-app/package.json
  react-app/src/pages/popup/components/language-selector.tsx
  react-app/src/pages/popup/components/shared/profile.tsx
  react-app/src/pages/popup/components/shared/searchBar/search-bar-wrapper.ts
  react-app/src/pages/popup/components/shared/searchBar/search-bar.tsx
  react-app/src/pages/popup/components/shared/seo.tsx
  react-app/src/pages/popup/components/store/list/item/addingKeyword/add-input.tsx
  react-app/src/pages/popup/components/store/list/item/keyword.tsx
  react-app/src/pages/popup/components/video/section/article/authorInfo/author-info.tsx
  react-app/src/pages/popup/components/video/section/article/video-article.tsx
  react-app/src/pages/popup/components/video/section/article/video-button.tsx
  react-app/src/pages/popup/components/video/section/article/videoInfo/video-infos.tsx
  react-app/src/pages/popup/pages/home/home.page.tsx
  react-app/utils/data/global-styles.ts
Labels: frontend, improvement

#194 fix: flickering error while changing state of input
  react-app/src/pages/popup/components/shared/error.tsx
  react-app/src/pages/popup/components/store/list/item/keyword.tsx
Labels: bug

#193 feat/contact with devs footer
  react-app/.github/ISSUE_TEMPLATE/bug_report.md
  react-app/.github/ISSUE_TEMPLATE/feature_request.md
  react-app/src/pages/popup/components/shared/github-link.tsx
  react-app/src/pages/popup/constant.ts
  react-app/src/pages/popup/pages/auth/auth.page.tsx
  react-app/src/pages/popup/pages/home/home.page.tsx
  react-app/utils/data/themes/dark-theme.ts
  react-app/utils/data/themes/light-theme.ts
Labels: enhancement, frontend

#179 improvement/display info about created keyword from contextMenu
  react-app/manifest.js
  react-app/package-lock.json
  react-app/package.json
  react-app/public/locales/en/translation.json
  react-app/public/locales/pl/translation.json
  react-app/src/pages/background/index.ts
  react-app/src/pages/content/components/error-toast.tsx
  react-app/src/pages/content/components/home/app.tsx
  react-app/utils/libs/internationalization/index.ts
Labels: frontend, improvement

#195 feat: add i18n for manifest
  react-app/manifest.js
  react-app/package-lock.json
  react-app/public/_locales/en/messages.json
  react-app/public/_locales/pl/messages.json
Labels: improvement

#199 fix/closing notification
  react-app/src/pages/content/components/home/app.tsx
Labels: bug, frontend

#200 fix/Translation on context menu
  react-app/src/pages/background/index.ts
Labels: bug, frontend

#202 fix/transition on auth page
  react-app/src/pages/popup/pages/home/home-wrapper.tsx
  react-app/utils/data/mixins/page-mixin.ts
Labels: bug, frontend

#203 improvement/decrease opacity for videos
  react-app/src/pages/popup/components/shared/button.ts
  react-app/src/pages/popup/components/video/section/article/video-article.tsx
Labels: frontend, improvement

#205 fix/watch later icon color on light
  react-app/src/pages/popup/components/video/section/article/videoInfo/video-infos.tsx
  react-app/utils/data/themes/dark-theme.ts
  react-app/utils/data/themes/light-theme.ts
Labels: bug, frontend

#206 fix/theme switch
  react-app/src/assets/img/dark-icon.svg
  react-app/src/assets/img/light-icon.svg
  react-app/src/pages/popup/components/language-selector.tsx
  react-app/src/pages/popup/components/shared/profile.tsx
  react-app/src/pages/popup/components/shared/searchBar/search-bar-wrapper.ts
  react-app/src/pages/popup/components/shared/searchBar/search-bar.tsx
  react-app/src/pages/popup/components/shared/theme-switch.tsx
  react-app/src/pages/popup/components/store/list/item/addingKeyword/add-input.tsx
  react-app/src/pages/popup/constant.ts
  react-app/utils/data/mixins/page-mixin.ts
Labels: bug, frontend

#207 Create dependabot.yml
  .github/dependabot.yml
Labels: improvement

#198 chore/Create README
  README.md
  nest-app/README.md
  react-app/README.md
  screenshots/auth-page.png
  screenshots/keywords-dark.png
  screenshots/keywords-light.png
  screenshots/notification.png
  screenshots/videos-dark.png
  screenshots/videos-light.png
Labels: documentation, frontend, backend

#210 Update dependabot.yml
  .github/dependabot.yml
Labels: bug, config

#211 Fix typo in README.md
  README.md
Labels: bug, documentation
