Repository PatrykKuniczak/YT_Notifier, pull requests merged in 2023-11, with the labels that each got.

#151 enhance/ add lincece and contributors
  nest-app/package.json
  package.json
  react-app/package.json
Labels: documentation

#130 feat: add support for i18n
  nest-app/src/key-words/key-words.controller.ts
  nest-app/src/key-words/key-words.service.ts
  react-app/package-lock.json
  react-app/package.json
  react-app/public/locales/en/translation.json
  react-app/public/locales/pl/translation.json
  react-app/src/assets/img/english-flag.svg
  react-app/src/assets/img/polish-flag.svg
  react-app/src/pages/content/components/home/app.tsx
  react-app/src/pages/internationalization.ts
  react-app/src/pages/popup/Popup.tsx
  react-app/src/pages/popup/components/language-selector.tsx
  react-app/src/pages/popup/components/shared/button.ts
  react-app/src/pages/popup/components/shared/delete-modal/modal-content.tsx
  react-app/src/pages/popup/components/shared/dropdown.tsx
  react-app/src/pages/popup/components/shared/error.tsx
  react-app/src/pages/popup/components/shared/errorSnackbar/use-error-snackbar.tsx
  react-app/src/pages/popup/components/shared/profile.tsx
  react-app/src/pages/popup/components/shared/searchBar/search-bar.tsx
  react-app/src/pages/popup/components/shared/theme-switch.tsx
  react-app/src/pages/popup/components/store/list/item/addingKeyword/add-input.tsx
  react-app/src/pages/popup/components/store/list/item/deleteButton/delete-button.tsx
  react-app/src/pages/popup/components/store/list/item/editButton/edit-button.tsx
  react-app/src/pages/popup/components/store/list/item/keyword.tsx
  react-app/src/pages/popup/components/video/section/article/video-article.tsx
  react-app/src/pages/popup/components/video/section/article/videoInfo/video-infos.tsx
  react-app/src/pages/popup/layouts/header-container.tsx
  react-app/src/pages/popup/layouts/navbar.tsx
  react-app/src/pages/popup/pages/auth/auth.page.tsx
  react-app/src/pages/popup/pages/home/use-home.ts
  react-app/src/pages/popup/routes/store.route.tsx
  react-app/utils/hooks/use-language-switch.ts
  react-app/utils/interfaces/index.ts
  react-app/utils/libs/http-client/index.ts
Labels: enhancement, frontend

#154 fix/Getting yt user data with user credentials on 'me' endpoint
  nest-app/src/swagger/response-examples/auth.response.ts
  nest-app/src/users/users.service.ts
Labels: bug, backend

#159 Feat/deploy for dev #70
  CONTRIBUTION.md
  nest-app/envs/example.env
  nest-app/package-lock.json
  nest-app/package.json
  nest-app/src/app.module.ts
  nest-app/src/database/config/typeorm.config.ts
  nest-app/src/main.ts
  package-lock.json
  package.json
  react-app/package-lock.json
  react-app/package.json
Labels: enhancement, backend

#160 fix/change packageJson file path
  react-app/manifest.ts
Labels: bug, frontend

#164 feat/create logger for fatal errors
  nest-app/src/app.module.ts
  nest-app/src/auth/auth.module.ts
  nest-app/src/database/migrations/1700421492489-create-loggers.ts
  nest-app/src/error-logs/dto/create-key-word.dto.ts
  nest-app/src/error-logs/error-logs.controller.ts
  nest-app/src/error-logs/error-logs.module.ts
  nest-app/src/error-logs/error-logs.service.ts
  nest-app/src/error-logs/model/error-logs.entity.ts
  nest-app/src/key-words/key-words.module.ts
  nest-app/src/key-words/key-words.service.ts
  nest-app/src/swagger/response-examples/error-logs.response.ts
  nest-app/src/user-yt-videos/user-yt-videos.module.ts
  nest-app/src/user-yt-videos/user-yt-videos.service.ts
  nest-app/src/users/model/users.entity.ts
  nest-app/src/users/users.module.ts
  nest-app/src/users/users.service.ts
Labels: enhancement, backend

#167 fix/using default fetch date properly
  nest-app/src/database/migrations/1700426454479-remove-default-date-from-lastFetch.ts
  nest-app/src/user-yt-videos/model/user-yt-videos.entity.ts
  nest-app/src/user-yt-videos/user-yt-videos.service.ts
Labels: bug, backend

#166 reafactor/rename keywords entity and restructure session dir
  CONTRIBUTION.md
  nest-app/src/auth/auth.module.ts
  nest-app/src/auth/sessions/model/sessions.entity.ts
  nest-app/src/auth/sessions/sessions.service.ts
  nest-app/src/database/migrations/1700425098398-rename-keywords-entity.ts
  nest-app/src/key-words/key-words.module.ts
  nest-app/src/key-words/key-words.service.ts
  nest-app/src/key-words/model/key-words.entity.ts
  nest-app/src/main.ts
  nest-app/src/users/model/users.entity.ts
Labels: backend, improvement

#163 fix/adjust code for work on deploy
  CONTRIBUTION.md
  nest-app/envs/example.env
  nest-app/src/app.module.ts
  nest-app/src/auth/auth.controller.ts
  nest-app/src/auth/googleAuth/google.strategy.ts
  nest-app/src/main.ts
Labels: bug, backend

#161 fix: duplicated page title
  react-app/src/pages/popup/pages/home/use-home.ts
Labels: bug, frontend

#162 improvement: change playlist on 'watch later' btn on navbar
  react-app/public/locales/en/translation.json
  react-app/public/locales/pl/translation.json
  react-app/src/pages/popup/layouts/navbar.tsx
  react-app/src/pages/popup/pages/home/home.page.tsx
  react-app/utils/interfaces/index.ts
Labels: frontend

#153 feat: add searching mechanism for videos
  react-app/src/pages/popup/components/video/section/article/authorInfo/author-info.tsx
  react-app/src/pages/popup/components/video/section/article/video-article.tsx
  react-app/src/pages/popup/components/video/section/article/videoInfo/video-infos.tsx
  react-app/src/pages/popup/components/video/section/skeleton/authorInfoSkeleton/author-info-skeleton.tsx
  react-app/src/pages/popup/components/video/section/skeleton/video-article-skeleton.tsx
  react-app/src/pages/popup/components/video/section/skeleton/videoInfoSkeleton/video-infos-skeleton.tsx
  react-app/src/pages/popup/routes/videos.route.tsx
  react-app/utils/interfaces/index.ts
Labels: frontend

#169 fix/session type on BE
  nest-app/index.d.ts
  nest-app/src/auth/auth.controller.ts
Labels: backend, improvement

#168 enhance/rename app
  CONTRIBUTION.md
  nest-app/README.md
  nest-app/package-lock.json
  nest-app/package.json
  nest-app/src/swagger/swagger.config.ts
  package-lock.json
  package.json
  react-app/README.md
  react-app/package-lock.json
  react-app/package.json
Labels: enhancement, frontend, backend

#171 update core template
  react-app/.gitignore
  react-app/manifest.js
  react-app/package-lock.json
  react-app/package.json
  react-app/src/pages/popup/Popup.tsx
  react-app/utils/core/hmr-core/plugins/custom-dynamic-import.ts
  react-app/utils/core/hmr-core/plugins/make-manifest.ts
  react-app/utils/core/hmr-core/plugins/watch-rebuild.ts
  react-app/utils/core/hmr-core/reload/constant.ts
  react-app/utils/core/hmr-core/reload/initReloadServer.ts
  react-app/utils/core/hmr-core/reload/interpreter/types.ts
  react-app/utils/core/hmr-core/reload/rollup.config.mjs
  react-app/utils/core/log.ts
  react-app/utils/core/manifest-parser/index.ts
  react-app/utils/core/plugins/add-hmr.ts
  react-app/utils/core/plugins/custom-dynamic-import.ts
  react-app/utils/core/plugins/make-manifest.ts
  react-app/utils/core/plugins/watch-rebuild.ts
  react-app/utils/core/reload/constant.ts
  react-app/utils/core/reload/initReloadClient.ts
  react-app/utils/core/reload/initReloadServer.ts
  react-app/utils/core/reload/injections/script.ts
  react-app/utils/core/reload/injections/view.ts
  react-app/utils/core/reload/interpreter/index.ts
  react-app/utils/core/reload/interpreter/types.ts
  react-app/utils/core/reload/rollup.config.mjs
  react-app/utils/core/reload/utils.ts
  react-app/vite.config.ts
Labels: enhancement

#149 Feat: error handlers components
  react-app/public/locales/en/translation.json
  react-app/public/locales/pl/translation.json
  react-app/src/pages/popup/Popup.tsx
  react-app/src/pages/popup/index.tsx
  react-app/src/pages/popup/pages/error/ErrorPage.tsx
  react-app/src/pages/popup/providers-wrapper.tsx
  react-app/utils/hooks/with-suspense.tsx
Labels: frontend

#176 fix: errors from previous PR's and move internationalization to libs
  react-app/.eslintrc
  react-app/src/global.d.ts
  react-app/src/pages/background/index.ts
  react-app/src/pages/content/components/home/app.tsx
  react-app/src/pages/popup/Popup.tsx
  react-app/src/pages/popup/components/language-selector.tsx
  react-app/src/pages/popup/components/shared/delete-modal/modal-content.tsx
  react-app/src/pages/popup/components/shared/error.tsx
  react-app/src/pages/popup/components/shared/errorSnackbar/use-error-snackbar.tsx
  react-app/src/pages/popup/components/shared/profile.tsx
  react-app/src/pages/popup/components/shared/searchBar/search-bar.tsx
  react-app/src/pages/popup/components/shared/theme-switch.tsx
  react-app/src/pages/popup/components/store/list/item/addingKeyword/add-input.tsx
  react-app/src/pages/popup/components/store/list/item/deleteButton/delete-button.tsx
  react-app/src/pages/popup/components/store/list/item/editButton/edit-button.tsx
  react-app/src/pages/popup/components/store/list/item/keyword.tsx
  react-app/src/pages/popup/components/store/list/item/store-value.tsx
  react-app/src/pages/popup/components/video/section/article/videoInfo/video-infos.tsx
  react-app/src/pages/popup/index.tsx
  react-app/src/pages/popup/layouts/navbar.tsx
  react-app/src/pages/popup/pages/auth/auth.page.tsx
  react-app/src/pages/popup/pages/error/ErrorPage.tsx
  react-app/src/pages/popup/pages/home/home.page.tsx
  react-app/src/pages/popup/pages/home/use-home.ts
  react-app/src/pages/popup/providers-wrapper.tsx
  react-app/src/pages/popup/routes/store.route.tsx
  react-app/src/pages/popup/routes/videos.route.tsx
  react-app/tsconfig.json
  react-app/utils/core/log.ts
  react-app/utils/hooks/use-language-switch.ts
  react-app/utils/hooks/with-error-boundary.tsx
  react-app/utils/libs/authentication/index.ts
  react-app/utils/libs/internationalization/index.ts
  react-app/vite.config.ts
Labels: bug, frontend
